// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB30zrQCMGOJyO5glFeGEcRZAPGs4uRaJU',
    appId: '1:623606238522:web:c52ed050ea95dc8df99403',
    messagingSenderId: '623606238522',
    projectId: 'drawingpath-c6aad',
    authDomain: 'drawingpath-c6aad.firebaseapp.com',
    databaseURL: 'https://drawingpath-c6aad-default-rtdb.firebaseio.com',
    storageBucket: 'drawingpath-c6aad.appspot.com',
    measurementId: 'G-ENC0JE6G1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAa4l6j03Mw-jiVki_mgX8rHMEpsk9pGY',
    appId: '1:623606238522:android:3f35f5deb4ac12f8f99403',
    messagingSenderId: '623606238522',
    projectId: 'drawingpath-c6aad',
    databaseURL: 'https://drawingpath-c6aad-default-rtdb.firebaseio.com',
    storageBucket: 'drawingpath-c6aad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc51B88QORU1oUUkakl4wMD8CterK2l3A',
    appId: '1:623606238522:ios:51b4634864afe68cf99403',
    messagingSenderId: '623606238522',
    projectId: 'drawingpath-c6aad',
    databaseURL: 'https://drawingpath-c6aad-default-rtdb.firebaseio.com',
    storageBucket: 'drawingpath-c6aad.appspot.com',
    iosBundleId: 'com.jideguru.flutterDrawingBoard',
  );
}
